 protected void login() throws Exception { login("user", "user"); } 